GMMS-6496 [Android] Fail build when okta properties are not available
MyPureCloud/mobiledx-samples-android pull request #110
Opened 2024-10-24 09:43 UTC by SzaszaGenesys

2024-10-24 11:16 UTC, mobichel requested changes

2024-10-24 11:16 UTC, mobichel commented on GCMessengerSDKSample/app/build.gradle
> +            throw new GradleException("okta.properties does not exist in the path (${oktaPropertiesFile.absolutePath}) and will be ignored.")
"and will be ignored" - this part of the message doesn’t make much sense now.

Do we have some default okta.properties which allows us to build app after git repo checkout?

If not it means we need to provide instructions how to get okta.properties in order to build application or bypass this exception if we want to build test app without authentication enabled.

2024-10-30 15:03 UTC, yarin-sason approved these changes

2024-10-30 15:14 UTC, SzaszaGenesys commented on GCMessengerSDKSample/app/src/main/java/com/genesys/cloud/messenger/sample/chat_form/OktaAuthenticationFragment.kt
> +                throw IllegalStateException("There are no proper okta.properties provided. Check Readme.md for more information.")
Done.

2024-10-31 08:32 UTC, mobichel approved these changes

2024-10-31 08:47 UTC, merged